basePath: /
definitions:
  dto.KubernetesDto:
    properties:
      num1:
        description: 第一个殊字
        example: 36
        type: integer
      num2:
        description: 第二个殊字
        example: 4
        type: integer
    type: object
host: localhost:8080
info:
  contact:
    email: hatech@hatech.com.cn
    name: hatech
    url: http://www.hatech.com.cn
  description: 提供加减乘除工具
  termsOfService: http://www.hatech.com.cn
  title: 计算器API
  version: "1.0"
paths:
  /add:
    get:
      consumes:
      - application/json
      description: 根据两个数字求和
      parameters:
      - default: 36
        description: 第一个数字
        in: query
        name: num1
        required: true
        type: integer
      - default: 4
        description: 第二个数字
        in: query
        name: num2
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: interface
      summary: 求和函数(get请求，【query，application/json方式】，路径中有参数)
      tags:
      - 运算相关函数
  /ave:
    post:
      consumes:
      - application/x-www-form-urlencoded
      description: 根据两个数字求平均值
      parameters:
      - default: 36
        description: 第一个数字
        in: query
        name: num1
        required: true
        type: integer
      - default: 4
        description: 第二个数字
        in: query
        name: num2
        required: true
        type: integer
      produces:
      - application/x-www-form-urlencoded
      responses:
        "200":
          description: OK
          schema:
            type: interface
      summary: 求平均值函数(post请求，【query，application/x-www-form-urlencoded方式】，路径没有参数)
      tags:
      - 运算相关函数
  /div:
    post:
      consumes:
      - application/json
      description: 根据两个数字求商
      parameters:
      - description: k8s对象
        in: body
        name: kubernetes
        required: true
        schema:
          $ref: '#/definitions/dto.KubernetesDto'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: interface
      summary: 求商函数(post请求，【body, application/json方式】，路径没有参数)
      tags:
      - 运算相关函数
  /mul:
    post:
      consumes:
      - application/json
      description: 根据两个数字求乘积
      parameters:
      - default: 36
        description: 第一个数字
        in: query
        name: num1
        required: true
        type: integer
      - default: 4
        description: 第二个数字
        in: query
        name: num2
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: interface
      summary: 求乘积函数(post请求，【query，application/json方式】，路径有参数)
      tags:
      - 运算相关函数
  /person:
    get:
      consumes:
      - application/json
      description: 获取人员信息
      parameters:
      - default: 张三
        description: 姓名
        in: query
        name: name
        required: true
        type: string
      - default: 44
        description: 年龄
        in: query
        name: age
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: interface
      summary: 获取人员信息(get请求，【query，application/json方式】，路径中有参数)
      tags:
      - Nacos操作
  /sub:
    get:
      consumes:
      - application/json
      description: 根据两个殊字求两个数字之减
      parameters:
      - default: 36
        description: 第一个数字
        in: query
        name: num1
        required: true
        type: integer
      - default: 4
        description: 第二个数字
        in: query
        name: num2
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: interface
      summary: 求差函数(get请求，【query，application/json方式】，路径上没有参数)
      tags:
      - 运算相关函数
swagger: "2.0"
